17:34:04  [INFO ] : 没有匹配到关键字
17:34:04  [INFO ] : 没有匹配到关键字
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"68540a73560f4266919004e42c3973ef"}
17:34:04  [INFO ] : 测试通过！
17:34:04  [INFO ] : 外部断言通过
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"a77ad4e26b99479cbce0b1548241dc36"}
17:34:04  [INFO ] : 测试通过！
17:34:04  [INFO ] : 外部断言通过
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"8d48d013ceb7424ba16cbffe4b6bd3cc"}
17:34:04  [INFO ] : 没有匹配到关键字
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"ebc90ff0ac03420e8330f50a4d1984a7"}
17:34:04  [INFO ] : 测试通过！
17:34:04  [INFO ] : 外部断言通过
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":201,"msg":"success"}
17:34:04  [INFO ] : 测试失败！
17:34:04  [INFO ] : 外部断言失败
17:34:04  [INFO ] : 没有匹配到关键字
17:34:04  [INFO ] : 没有匹配到关键字
17:34:04  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:04  [INFO ] : 测试通过！
17:34:04  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"f9b5346a52834352b35a8beb0d75a9db"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":406,"msg":"用户已经在别处登录"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"f8e5b3bbf39d4b40904ca045242acd84"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
17:34:05  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:05  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:05  [INFO ] : 外部断言失败
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
17:34:05  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:05  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:05  [INFO ] : 外部断言失败
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1201"}
17:34:05  [INFO ] : 测试失败！
17:34:05  [INFO ] : 外部断言失败
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1206"}
17:34:05  [INFO ] : 测试失败！
17:34:05  [INFO ] : 外部断言失败
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:05  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:05  [INFO ] : 测试通过！
17:34:05  [INFO ] : 外部断言通过
17:34:15  [ERROR] : org.apache.http.conn.ConnectTimeoutException: Connect to www.testingedu.com.cn:8081 [www.testingedu.com.cn/47.105.110.138] failed: connect timed out
org.apache.http.conn.ConnectTimeoutException: Connect to www.testingedu.com.cn:8081 [www.testingedu.com.cn/47.105.110.138] failed: connect timed out
	at inter.HttpClientKw.doPost(HttpClientKw.java:314) ~[classes/:?]
	at inter.KeywordOfInter.testPost(KeywordOfInter.java:39) ~[classes/:?]
	at Mail.b.e(b.java:80) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.11.jar:4.5.11]
	at inter.HttpClientKw.doPost(HttpClientKw.java:299) ~[classes/:?]
	... 29 more
17:34:15  [INFO ] : 在keyword中调试输出返回的结果是org.apache.http.conn.ConnectTimeoutException: Connect to www.testingedu.com.cn:8081 [www.testingedu.com.cn/47.105.110.138] failed: connect timed out
17:34:15  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:15  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2org.apache.http.conn.ConnectTimeoutException: Connect to www.testingedu.com.cn:8081 [www.testingedu.com.cn/47.105.110.138] failed: connect timed out
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2org.apache.http.conn.ConnectTimeoutException: Connect to www.testingedu.com.cn:8081 [www.testingedu.com.cn/47.105.110.138] failed: connect timed out
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:15  [INFO ] : 外部断言失败
17:34:15  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:15  [INFO ] : 测试通过！
17:34:15  [INFO ] : 外部断言通过
17:34:15  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:15  [INFO ] : 测试通过！
17:34:15  [INFO ] : 外部断言通过
17:34:15  [INFO ] : 在keyword中调试输出返回的结果是<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
17:34:15  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:15  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:15  [INFO ] : 外部断言失败
17:34:15  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:15  [INFO ] : 测试通过！
17:34:15  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
17:34:16  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:16  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:16  [INFO ] : 外部断言失败
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
17:34:16  [ERROR] : 解析失败，请检查jsonPath表达式
17:34:16  [ERROR] : com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.NullPointerException
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.16</h3></body></html>
	at inter.KeywordOfInter.assertSame(KeywordOfInter.java:157) ~[classes/:?]
	at Mail.b.e(b.java:113) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
17:34:16  [INFO ] : 外部断言失败
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"b292e66496b14af1931c471596c38b97"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"8c3b69090193419e921ee50854f649eb"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:16  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:16  [INFO ] : 测试通过！
17:34:16  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户名密码错误"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 没有匹配到关键字
17:34:17  [INFO ] : 没有匹配到关键字
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"a3b45d8ab63e44c599bc0d045b1d1521"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":406,"msg":"登录状态，不能注册"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:17  [INFO ] : 没有匹配到关键字
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"acc79db7c4a2477c861c8afc0d595ce1"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1206"}
17:34:17  [INFO ] : 测试失败！
17:34:17  [INFO ] : 外部断言失败
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"d05224f227ab49a7989e03e1c6687dd9"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:17  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:17  [INFO ] : 测试通过！
17:34:17  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 没有匹配到关键字
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"9b1574346bca4d889e539d8175d1ed11"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1458"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"f772e068189e4aceaf63e4488070c459"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:18  [INFO ] : 测试失败！
17:34:18  [INFO ] : 外部断言失败
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:18  [INFO ] : 没有匹配到关键字
17:34:18  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"651285eafdf5434aa8f0240034199929"}
17:34:18  [INFO ] : 测试通过！
17:34:18  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1459"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"c19dd74e56d94cb79a4c9b74cfd5ddc0"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:19  [INFO ] : 测试失败！
17:34:19  [INFO ] : 外部断言失败
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":402,"msg":"参数错误"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 没有匹配到关键字
17:34:19  [INFO ] : 没有匹配到关键字
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 没有匹配到关键字
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"fe10df3cfb244705822b7f2d8117f6b5"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:19  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"4bf8862587944268a8290a833f0d0d34"}
17:34:19  [INFO ] : 测试通过！
17:34:19  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 没有匹配到关键字
17:34:20  [INFO ] : 没有匹配到关键字
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"8a6d2cf4dc37484ebb70daede801d59d"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":401,"msg":"用户已被注册"}
17:34:20  [INFO ] : 测试失败！
17:34:20  [INFO ] : 外部断言失败
17:34:20  [INFO ] : 没有匹配到关键字
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1407"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 没有匹配到关键字
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"查询成功","nickname":"测试账号","id":"1407","describe":"这个账号，是一个测试注册的账号"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
17:34:20  [INFO ] : 没有匹配到关键字
17:34:20  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
17:34:20  [INFO ] : 测试通过！
17:34:20  [INFO ] : 外部断言通过
